# Define the input for grasp calculation: a point cloud
haf_grasping/GraspInput graspinput
---
# Define the result, if succeeded: defines grasp for gripper
haf_grasping/GraspOutput graspOutput
---
# Define a feedback message
std_msgs/String feedback
